version: 2

sources:
  - name: staging
  # for bigquery:
    database: imposing-vista-416522
    schema: trips_data_all

    tables:
      - name: green_tripdata
      - name: yellow_tripdata